Remove deprecated lines from husky pre-commit file

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,9 +1,6 @@
-#!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
-
 if ! npm run lint; then
-  printf "\033[0;31mCommit aborted: some files are not formatted with Prettier. Run 'npm run format' and stage the changes.\033[0m]\n"
-  exit 1
+    printf "\033[0;31mCommit aborted: some files are not formatted with Prettier. Run 'npm run format' and stage the changes.\033[0m]\n"
+    exit 1
 fi
 
 npx lint-staged
